In [1]:
import numpy as np
import pandas as pd

In [5]:
def drop_na_columns(df, percentage):
    missing_values_count = df.isnull().sum()
    # 데이터 세트의 값 중 몇 퍼센트가 누락되었는지 확인
    total_cells = np.product(df.shape)
    total_missing = missing_values_count.sum()

    (total_missing/total_cells) * 100

    # Percentage of NAN Values 
    NAN = [(c, df[c].isna().mean()*100) for c in df]
    NAN = pd.DataFrame(NAN, columns=["column_name", "percentage"])

    # Features with more than 50% of missing values.
    NAN = NAN[NAN.percentage > percentage]
    # NAN.sort_values("percentage", ascending=False)

    NAN_cols = NAN['column_name'].to_list()
    df_dropped_na = df.drop(NAN_cols,axis=1)
    print('Number of dropped columns', df.shape[1] - df_dropped_na.shape[1])
    
    return df_dropped_na

def drop_col_not_using(df):

    firebase_col = [s for s in df.columns if "firebase" in s]
    df_dropped_na = df.drop(firebase_col, axis=1)
    
    df_col = df_dropped_na.columns
    duplicated_col = [s for s in df_col if "_1" in s]
    app_info_col = [s for s in df_col if "app_info" in s]
    device_col = [s for s in df_col if "device" in s]
    traffic_col = [s for s in df_col if "traffic" in s]
    geo_col = [s for s in df_col if "geo" in s]
    # user_col =  [s for s in df_col if "user" in s]

    df_dropped_na.drop(duplicated_col, axis=1, inplace=True)
    df_dropped_na.drop(app_info_col, axis=1, inplace=True)
    df_dropped_na.drop(device_col, axis=1, inplace=True)
    df_dropped_na.drop(traffic_col, axis=1, inplace=True)
    df_dropped_na.drop(geo_col, axis=1, inplace=True)
    print('Number of dropped columns', df.shape[1] - df_dropped_na.shape[1])
    
    return df_dropped_na

In [2]:
activity = pd.read_csv("data/brazil_activity.csv")

/home/users/s17011720/.conda/envs/jupyter/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3166: DtypeWarning: Columns (1,2,3,40) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
asset = pd.read_csv("data/brazil_asset.csv")
draw = pd.read_csv("data/brazil_draw.csv")
stage = pd.read_csv("data/brazil_stage.csv")
tutorial = pd.read_csv("data/brazil_tutorial.csv")
play = pd.read_csv("data/brazil_play.csv")
ads1 = pd.read_csv("data/brazil_ads_1to5.csv")
ads2 = pd.read_csv("data/brazil_ads_6to10.csv")

In [6]:
activity_filtered = drop_na_columns(activity, 50)
activity_filtered = drop_col_not_using(activity_filtered)

Number of dropped columns 14
Number of dropped columns 42


In [8]:
activity_filtered.to_csv('column_filtered_data/activity_filtered.csv', index = False)

In [9]:
tutorial = pd.read_csv("data/brazil_tutorial.csv")

/home/users/s17011720/.conda/envs/jupyter/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3166: DtypeWarning: Columns (0,1,2,59) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [22]:
tutorial[tutorial[['event_params_ad_id','user_properties_ad_id', 'ga_session_id', 'ga_session_number']].isnull()]

KeyboardInterrupt: 

In [27]:
sub_df = tutorial[['event_params_ad_id','user_properties_ad_id', 'ga_session_id', 'ga_session_number']]

In [28]:
sub_df[sub_df['event_params_ad_id'].isnull()]

event_params_ad_id user_properties_ad_id  ga_session_id  \
290                    NaN                   NaN   1.618459e+09   
343                    NaN                   NaN   1.620814e+09   
345                    NaN                   NaN   1.618447e+09   
1243                   NaN                   NaN   1.618639e+09   
1254                   NaN                   NaN   1.618231e+09   
...                    ...                   ...            ...   
1008504                NaN                   NaN   1.619299e+09   
1008507                NaN                   NaN   1.619299e+09   
1008635                NaN                   NaN   1.618495e+09   
1008639                NaN                   NaN   1.619352e+09   
1008693                NaN                   NaN   1.619113e+09   

         ga_session_number  
290                    1.0  
343                    1.0  
345                    1.0  
1243                   1.0  
1254                   1.0  
...                    ...  
1008504                1.0  
1008507                1.0  
1008635                1.0  
1008639                1.0  
1008693                1.0  

[9194 rows x 4 columns]

In [21]:
tutorial.shape

(1008752, 89)

In [18]:
tutorial['event_params_ad_id'].unique()

array(['8c1573e7-f440-431e-b516-00c5b621fd63',
       '1d1ec878-3d36-46e5-a2cc-3bed46341679',
       '95511509-8065-4227-bd5a-a803ddbed7b6', ...,
       'f8521e5b-7898-4e05-859c-bd4271fb9c4c',
       '59927e26-6fdc-4e75-8b37-700e92d820b7',
       '25ecbd25-6bca-4aa1-98b9-d4b6ca0165c8'], dtype=object)

In [17]:
tutorial.head()

traffic_source_medium traffic_source_source traffic_source_name  event_date  \
0                   NaN                   NaN                 NaN    20210417   
1                   NaN                   NaN                 NaN    20210410   
2                   NaN                   NaN                 NaN    20210413   
3                   NaN                   NaN                 NaN    20210416   
4                   NaN                   NaN                 NaN    20210419   

    event_timestamp event_name                    event_params_ad_id  \
0  1618716504567000   tutorial  8c1573e7-f440-431e-b516-00c5b621fd63   
1  1618080730037000   tutorial  1d1ec878-3d36-46e5-a2cc-3bed46341679   
2  1618362123481000   tutorial  95511509-8065-4227-bd5a-a803ddbed7b6   
3  1618572315366000   tutorial  a42b11cd-da75-4043-897f-18c3f4d67c3e   
4  1618892539702000   tutorial  c1fb8a47-9bbb-4faa-935d-d533b985431a   

  firebase_screen_class  ga_session_id  engaged_session_event  ...  \
0   UnityPlayerActivity   1.618716e+09                    1.0  ...   
1   UnityPlayerActivity   1.618081e+09                    1.0  ...   
2   UnityPlayerActivity   1.618362e+09                    1.0  ...   
3   UnityPlayerActivity   1.618572e+09                    1.0  ...   
4   UnityPlayerActivity   1.618892e+09                    1.0  ...   

         geo_city  geo_sub_continent  geo_metro        app_info_id  \
0       Sao Paulo      South America  (not set)  kr.co.DrawHammer1   
1          Macapa      South America  (not set)  kr.co.DrawHammer1   
2             NaN      South America  (not set)  kr.co.DrawHammer1   
3  Patos de Minas      South America  (not set)  kr.co.DrawHammer1   
4       Sao Paulo      South America  (not set)  kr.co.DrawHammer1   

   app_info_version                       app_info_firebase_app_id  \
0             1.5.1  1:142569243604:android:31c6a5c81e681fd8210c41   
1             1.5.0  1:142569243604:android:31c6a5c81e681fd8210c41   
2             1.5.1  1:142569243604:android:31c6a5c81e681fd8210c41   
3             1.5.1  1:142569243604:android:31c6a5c81e681fd8210c41   
4             1.5.2  1:142569243604:android:31c6a5c81e681fd8210c41   

   app_info_install_source   stream_id  platform  items  
0      com.android.vending  2205916636   ANDROID     []  
1      com.android.vending  2205916636   ANDROID     []  
2      com.android.vending  2205916636   ANDROID     []  
3      com.android.vending  2205916636   ANDROID     []  
4      com.android.vending  2205916636   ANDROID     []  

[5 rows x 89 columns]

In [36]:
tutorial_filtered = drop_na_columns(tutorial, 50)
tutorial_filtered = drop_col_not_using(tutorial_filtered)

Number of dropped columns 18
Number of dropped columns 41


In [37]:
tutorial_filtered.head()

event_date   event_timestamp event_name  \
0    20210417  1618716504567000   tutorial   
1    20210410  1618080730037000   tutorial   
2    20210413  1618362123481000   tutorial   
3    20210416  1618572315366000   tutorial   
4    20210419  1618892539702000   tutorial   

                     event_params_ad_id  ga_session_id  engaged_session_event  \
0  8c1573e7-f440-431e-b516-00c5b621fd63   1.618716e+09                    1.0   
1  1d1ec878-3d36-46e5-a2cc-3bed46341679   1.618081e+09                    1.0   
2  95511509-8065-4227-bd5a-a803ddbed7b6   1.618362e+09                    1.0   
3  a42b11cd-da75-4043-897f-18c3f4d67c3e   1.618572e+09                    1.0   
4  c1fb8a47-9bbb-4faa-935d-d533b985431a   1.618892e+09                    1.0   

  tutorial_name  ga_session_number  tutorial_id  event_previous_timestamp  \
0    draw_start                1.0            1                       NaN   
1     stage_end                1.0            4              1.618081e+15   
2      draw_end                1.0            2              1.618362e+15   
3     stage_end                1.0            4              1.618572e+15   
4      draw_end                1.0            2              1.618893e+15   

   ...  user_level  user_level_timestamp first_open_time  \
0  ...           1      1618716504528000    1.618718e+12   
1  ...           1      1618080730037000    1.618081e+12   
2  ...           1      1618362123480000    1.618366e+12   
3  ...           1      1618572315366000    1.618574e+12   
4  ...           1      1618892539698000    1.618895e+12   

   first_open_time_timestamp ga_session_id_timestamp  \
0               1.618716e+15            1.618716e+15   
1               1.618081e+15            1.618081e+15   
2               1.618362e+15            1.618362e+15   
3               1.618572e+15            1.618572e+15   
4               1.618892e+15            1.618892e+15   

   user_first_touch_timestamp mobile_model_name   stream_id platform  items  
0                1.618716e+15               NaN  2205916636  ANDROID     []  
1                1.618081e+15               NaN  2205916636  ANDROID     []  
2                1.618362e+15               NaN  2205916636  ANDROID     []  
3                1.618572e+15               NaN  2205916636  ANDROID     []  
4                1.618892e+15               NaN  2205916636  ANDROID     []  

[5 rows x 30 columns]

In [38]:
tutorial_filtered.columns

Index(['event_date', 'event_timestamp', 'event_name', 'event_params_ad_id',
       'ga_session_id', 'engaged_session_event', 'tutorial_name',
       'ga_session_number', 'tutorial_id', 'event_previous_timestamp',
       'event_bundle_sequence_id', 'event_server_timestamp_offset',
       'user_pseudo_id', 'ga_session_number_timestamp',
       'user_properties_ad_id', 'ad_id_timestamp', 'cuid', 'cuid_timestamp',
       'frist_version', 'frist_version_timestamp', 'user_level',
       'user_level_timestamp', 'first_open_time', 'first_open_time_timestamp',
       'ga_session_id_timestamp', 'user_first_touch_timestamp',
       'mobile_model_name', 'stream_id', 'platform', 'items'],
      dtype='object')

In [34]:
tutorial_filtered['action_id'].unique()

array([3003, 3002, 3001, 1001])

In [43]:
tutorial_filtered['user_level'].unique()

array([  1,   2, 230,  14, 107,   3,  27,   4,  18,   7,  10,  61,  21,
        69,  32,  46,   8,   6,  38,  24,  13,  12,  11,   5,  35,  26,
        34,  93,   9,  25,  79,  30,  51,  15,  42,  37,  36,  83,  16,
        28,  44])

In [48]:
tutorial['user_level'].unique()

array([  1,   2, 230,  14, 107,   3,  27,   4,  18,   7,  10,  61,  21,
        69,  32,  46,   8,   6,  38,  24,  13,  12,  11,   5,  35,  26,
        34,  93,   9,  25,  79,  30,  51,  15,  42,  37,  36,  83,  16,
        28,  44])

In [74]:
tutorial[tutorial['user_level']==230][['user_level', 'ga_session_number']]

user_level  ga_session_number
2951           230                1.0
103727         230                1.0
507487         230                1.0
608401         230                1.0

In [81]:
tut = tutorial[tutorial['tutorial_id']==1][['event_params_ad_id','tutorial_id', 'user_level', 'ga_session_number']]

In [82]:
tut['ga_session_number'].unique()

array([ 1.,  2.,  3.,  6.,  5.,  4., nan, 11.,  7., 10., 15., 13., 12.,
       17.,  9., 14., 18.])

In [51]:
tutorial_filtered[tutorial_filtered['user_level']==44]['event_params_ad_id']

402185    9729467d-0164-4a33-a9c9-1e37e8c8e7b5
426702    9729467d-0164-4a33-a9c9-1e37e8c8e7b5
805528    9729467d-0164-4a33-a9c9-1e37e8c8e7b5
805545    9729467d-0164-4a33-a9c9-1e37e8c8e7b5
Name: event_params_ad_id, dtype: object

In [62]:
tutorial[tutorial['event_params_ad_id']=='9729467d-0164-4a33-a9c9-1e37e8c8e7b5'][['user_pseudo_id','event_date','user_level','tutorial_id']].sort_values('event_date')

user_pseudo_id  event_date  user_level  tutorial_id
486889  ebde9322d9d8b7c1646b5da034675314    20210420           1            3
487147  ebde9322d9d8b7c1646b5da034675314    20210420           1            4
781300  ebde9322d9d8b7c1646b5da034675314    20210420           1            2
890092  ebde9322d9d8b7c1646b5da034675314    20210420           1            1
402185  7b764bb91af45926af36c86ee62882b9    20210425          44            2
426702  7b764bb91af45926af36c86ee62882b9    20210425          44            1
805528  7b764bb91af45926af36c86ee62882b9    20210425          44            3
805545  7b764bb91af45926af36c86ee62882b9    20210425          44            4

In [118]:
df = pd.DataFrame(tutorial.groupby('user_pseudo_id')['user_level'].count())
df

user_level
user_pseudo_id                              
00002659c8d314d85bcb0565129b9c68           4
0000333428b0b9c006fdb2a4b56d99da           4
00003cf14f69b36df918bdabec2df163           4
0000429f2abb7398de3c57c40c9a0948           4
00006007c61092098d4a59f500597b58           4
...                                      ...
ffff64f49cffefc1b1e04cfed2d951af           4
ffff7745f72ad42fea1df9ff04d184c8           4
ffff7fc8ec9f8eca876313af95f0448d           4
ffff91d6f83ef5ca28e05c61608e8e26           4
ffffa3393058bbc57186b771d86079d6           4

[252540 rows x 1 columns]

In [125]:
over4row = df[df['user_level']>4]

In [127]:
user_pseudo_id = over4row.index.tolist()

In [133]:
sub = tutorial[tutorial['user_pseudo_id'].isin(user_pseudo_id)][['event_params_ad_id', 'user_pseudo_id', 'user_level']]
sub

event_params_ad_id  \
73       d85b49f0-fd80-4b27-8d4b-cf4724059b04   
74       0e245ae0-b283-48d6-99eb-bc1c43314a3d   
94       d85b49f0-fd80-4b27-8d4b-cf4724059b04   
127      8e694b18-7c66-422e-be9f-53de54e84e2f   
194      c18c79d2-d48b-4786-ad41-34184ad56341   
...                                       ...   
1007553  e2827edd-de11-4cb5-92c6-5711ea3241d4   
1007770  000ce6ec-9ada-41b3-93fa-ce622ee8c0f5   
1007883  b960dec6-632f-4ed2-9f3d-39210a7f019d   
1007974  cd67ee55-b9a6-4d32-8a77-20547863245c   
1008641  f1ca65b5-8dc4-4ec7-a281-c9188d3d8698   

                           user_pseudo_id  user_level  
73       53d57bcd189ab72a31f91255390a2466           1  
74       6b5e91c9156424d5382112c3c64b842a           1  
94       53d57bcd189ab72a31f91255390a2466           1  
127      a645d1170cb2707a2f5f0777ca688215           1  
194      dc29663d16f29d9754f7219f1b2e5c1e           1  
...                                   ...         ...  
1007553  1f8cb6662bfacd8ab913188ed777c19b           1  
1007770  d27e4e523ac82e557969b21ecc3650e5           1  
1007883  45eee6c71346834d58d76b91bb7024b1           1  
1007974  3260a4eedb7f05ec0d9439d4d7a55915           1  
1008641  dda212062b88c9ae078ebea87a98f2e3           1  

[8030 rows x 3 columns]

In [134]:
sub[sub['user_pseudo_id'] == '53d57bcd189ab72a31f91255390a2466']

event_params_ad_id  \
73      d85b49f0-fd80-4b27-8d4b-cf4724059b04   
94      d85b49f0-fd80-4b27-8d4b-cf4724059b04   
302546  d85b49f0-fd80-4b27-8d4b-cf4724059b04   
605493  d85b49f0-fd80-4b27-8d4b-cf4724059b04   
705971  d85b49f0-fd80-4b27-8d4b-cf4724059b04   

                          user_pseudo_id  user_level  
73      53d57bcd189ab72a31f91255390a2466           1  
94      53d57bcd189ab72a31f91255390a2466           1  
302546  53d57bcd189ab72a31f91255390a2466           1  
605493  53d57bcd189ab72a31f91255390a2466           1  
705971  53d57bcd189ab72a31f91255390a2466           1

In [69]:
tutorial.groupby(['event_params_ad_id'])['ga_session_number'].min()

event_params_ad_id
00018501-6eee-45e9-b5b5-7b50f966abd8    1.0
0001edb6-e7e7-4f74-8993-2bfc9347a959    1.0
0001ef07-c27e-4d91-a8bb-d0aa5f0d45e7    1.0
000289c6-779a-4b82-bab0-652fa477be1f    1.0
0002aec5-2842-4fa8-9b13-004ec60a5a2a    1.0
                                       ... 
fffe4cf6-ea7b-4377-af60-a019e460bd30    1.0
fffe5e96-fb11-462b-bb81-f3bb1911f618    1.0
ffffaa74-daa9-4fe1-a4bb-9e9c5853246f    1.0
ffffb6c8-7644-41b3-b334-f6035059539f    1.0
fffff9f7-8eeb-4ed0-855a-9d342b5a97ef    1.0
Name: ga_session_number, Length: 243281, dtype: float64

In [65]:
tutorial[tutorial['ga_session_number']!=1].shape

(20261, 89)

In [135]:
tutorial['ga_session_number'].unique()

array([ 1.,  3.,  2.,  4.,  5.,  6., nan, 13.,  7., 10., 11., 14., 12.,
        9., 15., 17., 18.])

In [149]:
tutorial_filtered[tutorial_filtered['event_params_ad_id'] == 'd4ab7a5a-c041-4351-966b-2bfe8307666b'].sort_values('event_timestamp')
# [['event_timestamp', 'event_date','event_params_ad_id', 'user_pseudo_id', 'tutorial_id', 'ga_session_number', 'user_level']]

event_date   event_timestamp event_name  \
563317    20210416  1618603370613000   tutorial   
66198     20210416  1618603378692000   tutorial   
873062    20210416  1618603378753000   tutorial   
254305    20210416  1618603391035000   tutorial   
966736    20210423  1619184029966000   tutorial   
966687    20210423  1619184035809000   tutorial   
873082    20210423  1619184035857000   tutorial   
966730    20210423  1619184045657000   tutorial   

                          event_params_ad_id  ga_session_id  \
563317  d4ab7a5a-c041-4351-966b-2bfe8307666b   1.618603e+09   
66198   d4ab7a5a-c041-4351-966b-2bfe8307666b   1.618603e+09   
873062  d4ab7a5a-c041-4351-966b-2bfe8307666b   1.618603e+09   
254305  d4ab7a5a-c041-4351-966b-2bfe8307666b   1.618603e+09   
966736  d4ab7a5a-c041-4351-966b-2bfe8307666b   1.619184e+09   
966687  d4ab7a5a-c041-4351-966b-2bfe8307666b   1.619184e+09   
873082  d4ab7a5a-c041-4351-966b-2bfe8307666b   1.619184e+09   
966730  d4ab7a5a-c041-4351-966b-2bfe8307666b   1.619184e+09   

        engaged_session_event tutorial_name  ga_session_number  tutorial_id  \
563317                    1.0    draw_start                1.0            1   
66198                     1.0      draw_end                1.0            2   
873062                    1.0   stage_start                1.0            3   
254305                    1.0     stage_end                1.0            4   
966736                    1.0    draw_start               18.0            1   
966687                    1.0      draw_end               18.0            2   
873082                    1.0   stage_start               18.0            3   
966730                    1.0     stage_end               18.0            4   

        event_previous_timestamp  ...  user_level  user_level_timestamp  \
563317                       NaN  ...           1      1618603370605000   
66198               1.618603e+15  ...           1      1618603378692000   
873062              1.618603e+15  ...           1      1618603378753000   
254305              1.618603e+15  ...           1      1618603391034000   
966736              1.618603e+15  ...           1      1619184029956000   
966687              1.619184e+15  ...           1      1619184035803000   
873082              1.619184e+15  ...           1      1619184035856000   
966730              1.619184e+15  ...           1      1619184045656000   

       first_open_time  first_open_time_timestamp ga_session_id_timestamp  \
563317    1.618607e+12               1.618603e+15            1.618603e+15   
66198     1.618607e+12               1.618603e+15            1.618603e+15   
873062    1.618607e+12               1.618603e+15            1.618603e+15   
254305    1.618607e+12               1.618603e+15            1.618603e+15   
966736    1.618607e+12               1.618603e+15            1.619184e+15   
966687    1.618607e+12               1.618603e+15            1.619184e+15   
873082    1.618607e+12               1.618603e+15            1.619184e+15   
966730    1.618607e+12               1.618603e+15            1.619184e+15   

        user_first_touch_timestamp mobile_model_name   stream_id platform  \
563317                1.618603e+15          SM-J250M  2205916636  ANDROID   
66198                 1.618603e+15          SM-J250M  2205916636  ANDROID   
873062                1.618603e+15          SM-J250M  2205916636  ANDROID   
254305                1.618603e+15          SM-J250M  2205916636  ANDROID   
966736                1.618603e+15          SM-J250M  2205916636  ANDROID   
966687                1.618603e+15          SM-J250M  2205916636  ANDROID   
873082                1.618603e+15          SM-J250M  2205916636  ANDROID   
966730                1.618603e+15          SM-J250M  2205916636  ANDROID   

        items  
563317     []  
66198      []  
873062     []  
254305     []  
966736     []  
966687     []  
873082     []  
966730     []  

[8 rows x 30 columns]

In [147]:
tutorial.columns

Index(['traffic_source_medium', 'traffic_source_source', 'traffic_source_name',
       'event_date', 'event_timestamp', 'event_name', 'event_params_ad_id',
       'firebase_screen_class', 'ga_session_id', 'engaged_session_event',
       'tutorial_name', 'ga_session_number', 'firebase_event_origin',
       'tutorial_id', 'firebase_screen_id', 'action_name', 'activity_id',
       'sub_name', 'sub_id', 'activity_name', 'action_id',
       'event_previous_timestamp', 'event_bundle_sequence_id',
       'event_server_timestamp_offset', 'user_pseudo_id', 'firebase_exp_3',
       'firebase_exp_3_timestamp', 'firebase_exp_3_1',
       'firebase_exp_3_timestamp_1', 'ga_session_number_1',
       'ga_session_number_timestamp', 'user_properties_ad_id',
       'ad_id_timestamp', 'firebase_exp_6', 'firebase_exp_6_timestamp',
       'firebase_exp_4', 'firebase_exp_4_timestamp', 'cuid', 'cuid_timestamp',
       'frist_version', 'frist_version_timestamp', 'firebase_exp_3_2',
       'firebase_exp_3_times

In [ ]:
play = pd.read_csv("data/brazil_play.csv")

In [ ]:
play_start = play[play['event_name']=='play_start']

In [ ]:
play_start.groupby('ad_id')['user_pseudo_id'].count()